/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package futsalapp;

import index.home;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class lihat_lapangan extends javax.swing.JFrame {

    /**
     * Creates new form lihat_lapangan
     */
    public lihat_lapangan() {
        initComponents();
        tampilDataLapangan();
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        textNama = new javax.swing.JTextField();
        textHarga = new javax.swing.JTextField();
        comboTipe = new javax.swing.JComboBox<>();
        comboStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "nama_Lapangan", "tipe_Lapangan", "harga", "status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoor", "Outdoor", " " }));
        comboTipe.setSelectedIndex(-1);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak Tersedia", " " }));
        comboStatus.setSelectedIndex(-1);

        jLabel1.setText("Nama Lapangan");

        jLabel2.setText("Harga");

        jLabel3.setText("Tipe Lapangan");

        jLabel4.setText("Status");

        jButton2.setBackground(new java.awt.Color(0, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 255, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNama)
                            .addComponent(textHarga)
                            .addComponent(comboTipe, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    Connection koneksi = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    FileWriter writer = null;

    try {

        // =========================================
        // KONEKSI DATABASE
        // =========================================
        koneksi = Koneksi.getKoneksi();

        String query = "SELECT id, nama_lapangan, tipe_lapangan, "
                + "harga_per_jam, status "
                + "FROM lapangan ORDER BY id";

        ps = koneksi.prepareStatement(query);
        rs = ps.executeQuery();

        // =========================================
        // MEMBACA LOGO
        // =========================================
        String logoBase64 = "";

        File logoFile = new File(
                "src/futsalapp/logo.png"
        );

        if (logoFile.exists()) {

            byte[] logoBytes = Files.readAllBytes(
                    logoFile.toPath()
            );

            logoBase64 = Base64.getEncoder()
                    .encodeToString(logoBytes);
        }

        // =========================================
        // FILE HTML
        // =========================================
        File file = File.createTempFile(
                "laporan_lapangan_",
                ".html"
        );

        writer = new FileWriter(file);

        // =========================================
        // HTML
        // =========================================
        writer.write("<!DOCTYPE html>");
        writer.write("<html lang='id'>");

        writer.write("<head>");

        writer.write("<meta charset='UTF-8'>");

        writer.write("<meta name='viewport' "
                + "content='width=device-width, initial-scale=1.0'>");

        writer.write("<title>Data Lapangan Futsal</title>");

        // =========================================
        // CSS
        // =========================================
        writer.write("<style>");

        writer.write("* {");
        writer.write("box-sizing: border-box;");
        writer.write("}");

        writer.write("body {");
        writer.write("margin: 0;");
        writer.write("padding: 40px;");
        writer.write("font-family: Arial, sans-serif;");
        writer.write("background: black;");
        writer.write("color: #1e293b;");
        writer.write("}");

        writer.write(".container {");
        writer.write("max-width: 1100px;");
        writer.write("margin: auto;");
        writer.write("}");

        // =========================================
        // HEADER HITAM
        // =========================================
        writer.write(".header {");
        writer.write("background: black;");
        writer.write("border-radius: 18px 18px 0 0;");
        writer.write("padding: 28px 32px;");
        writer.write("color: white;");
        writer.write("display: flex;");
        writer.write("align-items: center;");
        writer.write("justify-content: space-between;");
        writer.write("}");

        writer.write(".brand {");
        writer.write("display: flex;");
        writer.write("align-items: center;");
        writer.write("gap: 18px;");
        writer.write("}");

        // =========================================
        // LOGO
        // =========================================
        writer.write(".logo {");
        writer.write("width: 70px;");
        writer.write("height: 70px;");
        writer.write("object-fit: contain;");
        writer.write("background: white;");
        writer.write("border-radius: 50%;");
        writer.write("padding: 7px;");
        writer.write("}");

        writer.write(".title h1 {");
        writer.write("margin: 0;");
        writer.write("font-size: 28px;");
        writer.write("font-weight: 700;");
        writer.write("}");

        writer.write(".title p {");
        writer.write("margin: 6px 0 0;");
        writer.write("font-size: 16px;");
        writer.write("color: #d1fae5;");
        writer.write("}");

        // =========================================
        // TOMBOL CETAK
        // =========================================
        writer.write(".print-button {");
        writer.write("border: none;");
        writer.write("background: white;");
        writer.write("color: #047857;");
        writer.write("padding: 13px 22px;");
        writer.write("border-radius: 10px;");
        writer.write("font-size: 14px;");
        writer.write("font-weight: bold;");
        writer.write("cursor: pointer;");
        writer.write("}");

        writer.write(".print-button:hover {");
        writer.write("background: #ecfdf5;");
        writer.write("}");

        // =========================================
        // CONTENT CARD
        // =========================================
        writer.write(".content {");
        writer.write("background: white;");
        writer.write("padding: 35px;");
        writer.write("}");

        writer.write(".section-title {");
        writer.write("font-size: 25px;");
        writer.write("font-weight: bold;");
        writer.write("margin-bottom: 5px;");
        writer.write("}");

        writer.write(".section-subtitle {");
        writer.write("font-size: 16px;");
        writer.write("color: #94a3b8;");
        writer.write("margin-bottom: 30px;");
        writer.write("}");

        // =========================================
        // TABLE
        // =========================================
        writer.write("table {");
        writer.write("width: 100%;");
        writer.write("border-collapse: collapse;");
        writer.write("}");

        writer.write("th {");
        writer.write("background: black;");
        writer.write("color: #047857;");
        writer.write("padding: 15px;");
        writer.write("text-align: left;");
        writer.write("font-size: 14px;");
        writer.write("border-bottom: 2px solid #d1fae5;");
        writer.write("}");

        writer.write("td {");
        writer.write("padding: 17px 15px;");
        writer.write("border-bottom: 1px solid #e5e7eb;");
        writer.write("font-size: 14px;");
        writer.write("}");

        writer.write("tr:hover {");
        writer.write("background: #f8fafc;");
        writer.write("}");

        // =========================================
        // STATUS
        // =========================================
        writer.write(".badge {");
        writer.write("display: inline-block;");
        writer.write("padding: 7px 14px;");
        writer.write("border-radius: 20px;");
        writer.write("font-size: 12px;");
        writer.write("font-weight: bold;");
        writer.write("}");

        writer.write(".tersedia {");
        writer.write("background: #dcfce7;");
        writer.write("color: #16a34a;");
        writer.write("}");

        writer.write(".terpesan {");
        writer.write("background: #fee2e2;");
        writer.write("color: #dc2626;");
        writer.write("}");

        // =========================================
        // FOOTER
        // =========================================
        writer.write(".footer {");
        writer.write("background: #f8fafc;");
        writer.write("border-radius: 0 0 18px 18px;");
        writer.write("padding: 20px 32px;");
        writer.write("display: flex;");
        writer.write("justify-content: space-between;");
        writer.write("font-size: 13px;");
        writer.write("color: #94a3b8;");
        writer.write("}");

        // =========================================
        // RESPONSIVE
        // =========================================
        writer.write("@media(max-width: 700px) {");

        writer.write("body {");
        writer.write("padding: 15px;");
        writer.write("}");

        writer.write(".header {");
        writer.write("flex-direction: column;");
        writer.write("align-items: flex-start;");
        writer.write("gap: 20px;");
        writer.write("}");

        writer.write(".content {");
        writer.write("padding: 20px;");
        writer.write("}");

        writer.write("table {");
        writer.write("font-size: 12px;");
        writer.write("}");

        writer.write("th, td {");
        writer.write("padding: 10px;");
        writer.write("}");

        writer.write(".footer {");
        writer.write("flex-direction: column;");
        writer.write("gap: 8px;");
        writer.write("}");

        writer.write("}");

        // =========================================
        // PRINT
        // =========================================
        writer.write("@media print {");

        writer.write("body {");
        writer.write("background: white;");
        writer.write("padding: 0;");
        writer.write("}");

        writer.write(".print-button {");
        writer.write("display: none;");
        writer.write("}");

        writer.write(".header, .content, .footer {");
        writer.write("box-shadow: none;");
        writer.write("}");

        writer.write("}");

        writer.write("</style>");

        writer.write("</head>");

        // =========================================
        // BODY
        // =========================================
        writer.write("<body>");

        writer.write("<div class='container'>");

        // =========================================
        // HEADER
        // =========================================
        writer.write("<div class='header'>");

        writer.write("<div class='brand'>");

        if (!logoBase64.isEmpty()) {

            writer.write(
                    "<img class='logo' "
                    + "src='data:image/jpeg;base64,"
                    + logoBase64
                    + "'>"
            );

        } else {

            writer.write(
                    "<div class='logo' "
                    + "style='display:flex;"
                    + "align-items:center;"
                    + "justify-content:center;"
                    + "font-size:35px;'>"
                    + "⚽"
                    + "</div>"
            );
        }

        writer.write("<div class='title'>");

        writer.write("<h1>FUTSAL ARENA</h1>");

        writer.write(
                "<p>Sistem Informasi Lapangan Futsal</p>"
        );

        writer.write("</div>");

        writer.write("</div>");

        // =========================================
        // BUTTON
        // =========================================
        writer.write(
                "<button class='print-button' "
                + "onclick='window.print()'>"
                + "🖨 Cetak"
                + "</button>"
        );

        writer.write("</div>");

        // =========================================
        // CONTENT
        // =========================================
        writer.write("<div class='content'>");

        writer.write(
                "<div class='section-title'>"
                + "Daftar Lapangan"
                + "</div>"
        );

        writer.write(
                "<div class='section-subtitle'>"
                + "Informasi lapangan futsal yang tersedia"
                + "</div>"
        );

        // =========================================
        // TABLE
        // =========================================
        writer.write("<table>");

        writer.write("<thead>");

        writer.write("<tr>");

        writer.write("<th>No</th>");
        writer.write("<th>Nama Lapangan</th>");
        writer.write("<th>Tipe Lapangan</th>");
        writer.write("<th>Harga / Jam</th>");
        writer.write("<th>Status</th>");

        writer.write("</tr>");

        writer.write("</thead>");

        writer.write("<tbody>");

        // =========================================
        // DATA DATABASE
        // =========================================
        int nomor = 1;

        while (rs.next()) {

            String nama = rs.getString("nama_lapangan");

            String tipe = rs.getString("tipe_lapangan");

            int harga = rs.getInt("harga_per_jam");

            String status = rs.getString("status");

            String classStatus;

            if (status.equalsIgnoreCase("Tersedia")) {
                classStatus = "tersedia";
            } else {
                classStatus = "terpesan";
            }

            // format 100000 -> 100.000
            String hargaFormat = String.format(
                    "%,d",
                    harga
            ).replace(",", ".");

            writer.write("<tr>");

            writer.write(
                    "<td>"
                    + nomor
                    + "</td>"
            );

            writer.write(
                    "<td><strong>"
                    + nama
                    + "</strong></td>"
            );

            writer.write(
                    "<td>"
                    + tipe
                    + "</td>"
            );

            writer.write(
                    "<td><strong>Rp "
                    + hargaFormat
                    + "</strong></td>"
            );

            writer.write(
                    "<td>"
                    + "<span class='badge "
                    + classStatus
                    + "'>"
                    + status
                    + "</span>"
                    + "</td>"
            );

            writer.write("</tr>");

            nomor++;
        }

        writer.write("</tbody>");

        writer.write("</table>");

        writer.write("</div>");

        // =========================================
        // FOOTER
        // =========================================
        writer.write("<div class='footer'>");

        writer.write(
                "<span>© 2026 Futsal Arena</span>"
        );

        writer.write(
                "<span>Dicetak melalui Sistem Informasi Futsal</span>"
        );

        writer.write("</div>");

        writer.write("</div>");

        writer.write("</body>");

        writer.write("</html>");

        // =========================================
        // SIMPAN & BUKA BROWSER
        // =========================================
        writer.close();

        Desktop.getDesktop().browse(
                file.toURI()
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (IOException e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal membuat laporan: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

    } finally {

        try {

            if (rs != null) {
                rs.close();
            }

            if (ps != null) {
                ps.close();
            }

            if (koneksi != null) {
                koneksi.close();
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        
        if (baris != -1) {
        String nama = jTable1.getValueAt(baris, 1).toString();
        String tipe = jTable1.getValueAt(baris, 2).toString();
        String harga = jTable1.getValueAt(baris, 3).toString();
        String status = jTable1.getValueAt(baris, 4).toString();

        textNama.setText(nama);
        textHarga.setText(harga);

        comboTipe.setSelectedItem(tipe);
        comboStatus.setSelectedItem(status);
    }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int baris = jTable1.getSelectedRow();

        // Belum pilih data
        if (baris == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Silakan pilih data lapangan terlebih dahulu!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE
        );

}

    // Validasi nama
    if (textNama.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Nama lapangan tidak boleh kosong!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Validasi harga
    if (textHarga.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Harga tidak boleh kosong!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try {

        int id = Integer.parseInt(
                jTable1.getValueAt(baris, 0).toString()
        );

        String nama = textNama.getText().trim();

        int harga = Integer.parseInt(
                textHarga.getText().trim()
        );

        String tipe = comboTipe.getSelectedItem().toString();

        String status = comboStatus.getSelectedItem().toString();

        Connection koneksi = Koneksi.getKoneksi();

        String sql = "UPDATE lapangan SET "
                + "nama_lapangan = ?, "
                + "tipe_lapangan = ?, "
                + "harga_per_jam = ?, "
                + "status = ? "
                + "WHERE id = ?";

        PreparedStatement ps =
                koneksi.prepareStatement(sql);

        ps.setString(1, nama);
        ps.setString(2, tipe);
        ps.setInt(3, harga);
        ps.setString(4, status);
        ps.setInt(5, id);

        ps.executeUpdate();

        ps.close();
        koneksi.close();

        JOptionPane.showMessageDialog(
                this,
                "Data lapangan berhasil diupdate!",
                "Berhasil",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Refresh tabel
        tampilDataLapangan();

        // Kosongkan form
        textNama.setText("");
        textHarga.setText("");
        comboTipe.setSelectedIndex(-1);
        comboStatus.setSelectedIndex(-1);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Harga harus berupa angka!",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal update data:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }   

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int baris = jTable1.getSelectedRow();

    // Belum pilih data
    if (baris == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Silakan pilih data yang ingin dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Ambil ID
    int id = Integer.parseInt(
            jTable1.getValueAt(baris, 0).toString()
    );

    // Konfirmasi
    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data lapangan ini?\n\n"
            + "Nama: "
            + jTable1.getValueAt(baris, 1),
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (konfirmasi != JOptionPane.YES_OPTION) {
        return;
    }

    try {

        Connection koneksi = Koneksi.getKoneksi();

        String sql =
                "DELETE FROM lapangan WHERE id = ?";

        PreparedStatement ps =
                koneksi.prepareStatement(sql);

        ps.setInt(1, id);

        ps.executeUpdate();

        ps.close();
        koneksi.close();

        JOptionPane.showMessageDialog(
                this,
                "Data lapangan berhasil dihapus!",
                "Berhasil",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Refresh tabel
        tampilDataLapangan();

        // Kosongkan form
        textNama.setText("");
        textHarga.setText("");
        comboTipe.setSelectedIndex(-1);
        comboStatus.setSelectedIndex(-1);

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal menghapus data:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        home halamanHome = new home();
        halamanHome.setLocationRelativeTo(null);
        halamanHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihat_lapangan().setVisible(true);
            }
        });
    }
    
    private void tampilDataLapangan() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Lapangan");
    model.addColumn("Tipe Lapangan");
    model.addColumn("Harga/Jam");
    model.addColumn("Status");

    try {
        Connection koneksi = Koneksi.getKoneksi();

        String query = "SELECT id, nama_lapangan, tipe_lapangan, "
                     + "harga_per_jam, status "
                     + "FROM lapangan "
                     + "ORDER BY id";

        PreparedStatement ps = koneksi.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("nama_lapangan"),
                rs.getString("tipe_lapangan"),
                rs.getInt("harga_per_jam"),
                rs.getString("status")
            });
        }

        jTable1.setModel(model);

        rs.close();
        ps.close();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Gagal menampilkan data: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JComboBox<String> comboTipe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables
}
